export { default as Header } from './common/Header'
export { default as Footer } from './common/Footer'
export { default as Hero } from './home/Hero'
export { default as Claim } from './home/Claim'
export { default as Evms } from './home/Evms'
export { default as Trending } from './home/Trending'
export { default as Recent } from './home/Recent'
export { default as Proposition } from './home/Proposition'